"""add_state_pension_rates

Revision ID: 1d43402c6c27
Revises: d741657e141a
Create Date: 2025-03-16 20:55:28.037201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d43402c6c27'
down_revision: Union[str, None] = 'd741657e141a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('state_pension_pessimistic_rate', 
                                      sa.Numeric(precision=10, scale=4), 
                                      nullable=False, 
                                      server_default='1.0'))
    op.add_column('settings', sa.Column('state_pension_realistic_rate', 
                                      sa.Numeric(precision=10, scale=4), 
                                      nullable=False, 
                                      server_default='1.5'))
    op.add_column('settings', sa.Column('state_pension_optimistic_rate', 
                                      sa.Numeric(precision=10, scale=4), 
                                      nullable=False, 
                                      server_default='2.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'state_pension_optimistic_rate')
    op.drop_column('settings', 'state_pension_realistic_rate')
    op.drop_column('settings', 'state_pension_pessimistic_rate')
    # ### end Alembic commands ###
