"""Adding task_metadata

Revision ID: 2339bedbeb28
Revises: e6ef58a20164
Create Date: 2025-02-19 22:15:38.050385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2339bedbeb28'
down_revision: Union[str, None] = 'e6ef58a20164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status', sa.Column('task_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_status', 'task_metadata')
    # ### end Alembic commands ###
