"""Add created_at to PensionStateStatement

Revision ID: 294ee7b14793
Revises: 24c86d154d2f
Create Date: 2025-03-20 17:20:11.950719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294ee7b14793'
down_revision: Union[str, None] = '24c86d154d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_state_statements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_state_statements', 'created_at')
    # ### end Alembic commands ###
