"""Update finance columns from float to numeric

Revision ID: 2eaaf780922b
Revises: 56c3fd9bb347
Create Date: 2025-02-15 10:06:59.910862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaaf780922b'
down_revision: Union[str, None] = '56c3fd9bb347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_pensions', 'matching_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('company_pensions', 'max_employer_contribution',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('contribution_steps', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('etf_allocations', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('etf_allocations', 'units_bought',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=False)
    op.alter_column('etf_prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('etfs', 'fund_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('etfs', 'ter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('etfs', 'last_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('etfs', 'ytd_return',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('etfs', 'one_year_return',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('etfs', 'volatility_30d',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('etfs', 'sharpe_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('insurance_pensions', 'guaranteed_interest',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('insurance_pensions', 'expected_return',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('pension_contributions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('pension_contributions', 'planned_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('pensions', 'initial_capital',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('pensions', 'current_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pensions', 'current_value',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pensions', 'initial_capital',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pension_contributions', 'planned_amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pension_contributions', 'amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('insurance_pensions', 'expected_return',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('insurance_pensions', 'guaranteed_interest',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('etfs', 'sharpe_ratio',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'volatility_30d',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'one_year_return',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'ytd_return',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'last_price',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'ter',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etfs', 'fund_size',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('etf_prices', 'price',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('etf_allocations', 'units_bought',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('etf_allocations', 'amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('contribution_steps', 'amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('company_pensions', 'max_employer_contribution',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('company_pensions', 'matching_percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
