"""update etf cascade constraints

Revision ID: 2ed2724c0918
Revises: a4f3babaddfb
Create Date: 2025-02-22 22:09:20.222606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed2724c0918'
down_revision: Union[str, None] = 'a4f3babaddfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pension_etf_etf_id_fkey', 'pension_etf', type_='foreignkey')
    op.create_foreign_key(None, 'pension_etf', 'etfs', ['etf_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pension_etf', type_='foreignkey')
    op.create_foreign_key('pension_etf_etf_id_fkey', 'pension_etf', 'etfs', ['etf_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
