"""Update ETF with ISIN

Revision ID: 36e722c0ca7e
Revises: 8d1e6ba6757e
Create Date: 2025-02-14 10:26:33.496748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e722c0ca7e'
down_revision: Union[str, None] = '8d1e6ba6757e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etfs', sa.Column('isin', sa.String(), nullable=True))
    op.alter_column('etfs', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_etfs_isin'), 'etfs', ['isin'], unique=True)
    op.create_index(op.f('ix_etfs_symbol'), 'etfs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etfs_symbol'), table_name='etfs')
    op.drop_index(op.f('ix_etfs_isin'), table_name='etfs')
    op.alter_column('etfs', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('etfs', 'isin')
    # ### end Alembic commands ###
