"""Added asset_class to ETF

Revision ID: 3b6fb573d60c
Revises: 36e722c0ca7e
Create Date: 2025-02-14 11:55:49.403490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6fb573d60c'
down_revision: Union[str, None] = '36e722c0ca7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etfs', sa.Column('asset_class', sa.String(), nullable=True))
    op.add_column('etfs', sa.Column('last_price', sa.Float(), nullable=True))
    op.add_column('etfs', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('etfs', sa.Column('ytd_return', sa.Float(), nullable=True))
    op.add_column('etfs', sa.Column('one_year_return', sa.Float(), nullable=True))
    op.add_column('etfs', sa.Column('volatility_30d', sa.Float(), nullable=True))
    op.add_column('etfs', sa.Column('sharpe_ratio', sa.Float(), nullable=True))
    op.alter_column('etfs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('etfs', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('etfs', 'domicile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('etfs', 'inception_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('etfs', 'fund_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('etfs', 'ter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('etfs', 'distribution_policy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_etfs_isin', table_name='etfs')
    op.create_index(op.f('ix_etfs_id'), 'etfs', ['id'], unique=False)
    op.drop_column('etfs', 'extra_data')
    op.drop_column('etfs', 'description')
    op.drop_column('etfs', 'provider')
    op.drop_column('etfs', 'replication_method')
    op.drop_column('etfs', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etfs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('etfs', sa.Column('replication_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('etfs', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('etfs', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('etfs', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_etfs_id'), table_name='etfs')
    op.create_index('ix_etfs_isin', 'etfs', ['isin'], unique=True)
    op.alter_column('etfs', 'distribution_policy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('etfs', 'ter',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('etfs', 'fund_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('etfs', 'inception_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('etfs', 'domicile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('etfs', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('etfs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('etfs', 'sharpe_ratio')
    op.drop_column('etfs', 'volatility_30d')
    op.drop_column('etfs', 'one_year_return')
    op.drop_column('etfs', 'ytd_return')
    op.drop_column('etfs', 'last_update')
    op.drop_column('etfs', 'last_price')
    op.drop_column('etfs', 'asset_class')
    # ### end Alembic commands ###
