"""per_pension_scenario_rates_all_types

Revision ID: 407d2b71598c
Revises: ee2c20c81e44
Create Date: 2026-02-23 12:29:17.025448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407d2b71598c'
down_revision: Union[str, None] = 'ee2c20c81e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_company', sa.Column('pessimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_company', sa.Column('realistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_company', sa.Column('optimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_etf', sa.Column('pessimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_etf', sa.Column('realistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_etf', sa.Column('optimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_insurance', sa.Column('pessimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_insurance', sa.Column('realistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_insurance', sa.Column('optimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    # Migrate existing data: guaranteed_interest/expected_return were already stored as % (1.1 = 1.1%)
    # despite code comments claiming raw decimal format — copy values as-is
    op.execute("""
        UPDATE pension_insurance SET
            pessimistic_rate = guaranteed_interest,
            realistic_rate = expected_return
        WHERE guaranteed_interest IS NOT NULL OR expected_return IS NOT NULL
    """)
    op.drop_column('pension_insurance', 'guaranteed_interest')
    op.drop_column('pension_insurance', 'expected_return')
    op.add_column('pension_state', sa.Column('pessimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_state', sa.Column('realistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('pension_state', sa.Column('optimistic_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_state', 'optimistic_rate')
    op.drop_column('pension_state', 'realistic_rate')
    op.drop_column('pension_state', 'pessimistic_rate')
    op.add_column('pension_insurance', sa.Column('expected_return', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('pension_insurance', sa.Column('guaranteed_interest', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.drop_column('pension_insurance', 'optimistic_rate')
    op.drop_column('pension_insurance', 'realistic_rate')
    op.drop_column('pension_insurance', 'pessimistic_rate')
    op.drop_column('pension_etf', 'optimistic_rate')
    op.drop_column('pension_etf', 'realistic_rate')
    op.drop_column('pension_etf', 'pessimistic_rate')
    op.drop_column('pension_company', 'optimistic_rate')
    op.drop_column('pension_company', 'realistic_rate')
    op.drop_column('pension_company', 'pessimistic_rate')
    # ### end Alembic commands ###
