"""replace withdrawal_rate with withdrawal_until_age and capital_depletion

Revision ID: 423c89c7b70a
Revises: f331e8e8f325
Create Date: 2026-03-18 22:06:04.092134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423c89c7b70a'
down_revision: Union[str, None] = 'f331e8e8f325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('retirement_gap_config', sa.Column('withdrawal_until_age', sa.Integer(), nullable=False, server_default='90'))
    op.add_column('retirement_gap_config', sa.Column('capital_depletion', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('retirement_gap_config', 'withdrawal_rate')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_gap_config', sa.Column('withdrawal_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    op.drop_column('retirement_gap_config', 'capital_depletion')
    op.drop_column('retirement_gap_config', 'withdrawal_until_age')
    # ### end Alembic commands ###
