"""add invested_amount to pension_etf

Revision ID: 4acc980b5028
Revises: 587e7e4c3516
Create Date: 2026-02-28 09:38:21.338548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acc980b5028'
down_revision: Union[str, None] = '587e7e4c3516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_etf', sa.Column('invested_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_etf', 'invested_amount')
    # ### end Alembic commands ###
