"""add_modular_data_sources

Revision ID: 587e7e4c3516
Revises: 660f90bb2113
Create Date: 2026-02-27 17:30:07.970762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '587e7e4c3516'
down_revision: Union[str, None] = '660f90bb2113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_configs',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('supports_search', sa.Boolean(), nullable=False),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('etf_source_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etf_id'], ['etfs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_configs.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'source_id', name='uix_etf_source_symbol')
    )
    # Add columns with server_default so existing rows get a value
    op.add_column('etf_prices', sa.Column('source', sa.String(), nullable=False, server_default='yfinance'))
    op.add_column('etf_prices', sa.Column('is_adjusted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Migrate existing rows (server_default already handles this, but explicit is clearer)
    op.execute("UPDATE etf_prices SET source = 'yfinance' WHERE source IS NULL")
    op.execute("UPDATE etf_prices SET is_adjusted = false WHERE is_adjusted IS NULL")
    # Update unique constraint: (etf_id, date) → (etf_id, date, source)
    op.drop_constraint('uix_etf_price_date', 'etf_prices', type_='unique')
    op.create_unique_constraint('uix_etf_price_date_source', 'etf_prices', ['etf_id', 'date', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_etf_price_date_source', 'etf_prices', type_='unique')
    op.create_unique_constraint('uix_etf_price_date', 'etf_prices', ['etf_id', 'date'])
    op.drop_column('etf_prices', 'is_adjusted')
    op.drop_column('etf_prices', 'source')
    op.drop_table('etf_source_symbols')
    op.drop_table('data_source_configs')
    # ### end Alembic commands ###
