"""Adding exchange rates for all currencies to EUR - v2

Revision ID: 5e17b114e90b
Revises: a7fdd1787696
Create Date: 2025-02-15 10:38:24.914662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e17b114e90b'
down_revision: Union[str, None] = 'a7fdd1787696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
