"""remove_etf_allocation_tables

Revision ID: 60dd4902f9d5
Revises: 2ed2724c0918
Create Date: 2025-02-22 23:08:31.778108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dd4902f9d5'
down_revision: Union[str, None] = '2ed2724c0918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pension_etf_allocation_history_id', table_name='pension_etf_allocation_history')
    op.drop_table('pension_etf_allocation_history')
    op.drop_index('ix_pension_etf_allocation_plan_id', table_name='pension_etf_allocation_plan')
    op.drop_table('pension_etf_allocation_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_etf_allocation_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pension_etf_contribution_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('etf_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['etf_id'], ['etfs.id'], name='pension_etf_allocation_plan_etf_id_fkey'),
    sa.ForeignKeyConstraint(['pension_etf_contribution_plan_id'], ['pension_etf_contribution_plan.id'], name='pension_etf_allocation_plan_pension_etf_contribution_plan__fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pension_etf_allocation_plan_pkey')
    )
    op.create_index('ix_pension_etf_allocation_plan_id', 'pension_etf_allocation_plan', ['id'], unique=False)
    op.create_table('pension_etf_allocation_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pension_etf_contribution_history_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('etf_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('units', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['etf_id'], ['etfs.id'], name='pension_etf_allocation_history_etf_id_fkey'),
    sa.ForeignKeyConstraint(['pension_etf_contribution_history_id'], ['pension_etf_contribution_history.id'], name='pension_etf_allocation_histor_pension_etf_contribution_his_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pension_etf_allocation_history_pkey')
    )
    op.create_index('ix_pension_etf_allocation_history_id', 'pension_etf_allocation_history', ['id'], unique=False)
    # ### end Alembic commands ###
