"""add retirement_gap_config table

Revision ID: 660f90bb2113
Revises: 407d2b71598c
Create Date: 2026-02-27 09:50:34.927704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660f90bb2113'
down_revision: Union[str, None] = '407d2b71598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retirement_gap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('net_monthly_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('desired_monthly_pension', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('replacement_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('withdrawal_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retirement_gap_config')
    # ### end Alembic commands ###
