"""rename_notes_to_note_in_pension_company_statements

Revision ID: 79bb3d029563
Revises: 5a7cdfd891bf
Create Date: 2025-03-05 09:20:51.547286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bb3d029563'
down_revision: Union[str, None] = '5a7cdfd891bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
