"""make_insurance_fields_nullable

Revision ID: 7a746d53ca0a
Revises: 153e30417be6
Create Date: 2025-03-06 11:11:00.464431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a746d53ca0a'
down_revision: Union[str, None] = '153e30417be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pension_insurance', 'contract_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pension_insurance', 'guaranteed_interest',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('pension_insurance', 'expected_return',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pension_insurance', 'expected_return',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('pension_insurance', 'guaranteed_interest',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('pension_insurance', 'contract_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
