"""Add exchange rate errors table

Revision ID: 86948fc38cbb
Revises: add_exchange_rate_errors
Create Date: 2025-02-15 22:55:27.698290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86948fc38cbb'
down_revision: Union[str, None] = 'add_exchange_rate_errors'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchange_rate_errors_resolved', table_name='exchange_rate_errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_exchange_rate_errors_resolved', 'exchange_rate_errors', ['resolved'], unique=False)
    # ### end Alembic commands ###
