"""Add note fields to contribution steps

Revision ID: 8859fb76f733
Revises: 5aff8326ecec
Create Date: 2025-02-24 12:07:39.109805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8859fb76f733'
down_revision: Union[str, None] = '5aff8326ecec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_company_contribution_plan_steps', sa.Column('note', sa.String(), nullable=True))
    op.add_column('pension_etf_contribution_plan_steps', sa.Column('note', sa.String(), nullable=True))
    op.add_column('pension_insurance_contribution_plan_steps', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_insurance_contribution_plan_steps', 'note')
    op.drop_column('pension_etf_contribution_plan_steps', 'note')
    op.drop_column('pension_company_contribution_plan_steps', 'note')
    # ### end Alembic commands ###
