"""Changeing cascadings

Revision ID: 88d21139ee3f
Revises: 04d2a26e12f9
Create Date: 2025-02-19 21:42:34.099361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d21139ee3f'
down_revision: Union[str, None] = '04d2a26e12f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_status_id', table_name='task_status')
    op.drop_table('task_status')
    op.drop_constraint('pension_etf_etf_id_fkey', 'pension_etf', type_='foreignkey')
    op.create_foreign_key(None, 'pension_etf', 'etfs', ['etf_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('pension_etf', 'is_existing_investment')
    op.drop_column('pension_etf', 'realize_historical_contributions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_etf', sa.Column('realize_historical_contributions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('pension_etf', sa.Column('is_existing_investment', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pension_etf', type_='foreignkey')
    op.create_foreign_key('pension_etf_etf_id_fkey', 'pension_etf', 'etfs', ['etf_id'], ['id'])
    op.create_table('task_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='task_status_pkey')
    )
    op.create_index('ix_task_status_id', 'task_status', ['id'], unique=False)
    # ### end Alembic commands ###
