"""add status dates to state pension

Revision ID: 94185ab6b930
Revises: bd92dd5a3933
Create Date: 2025-03-22 20:11:35.004261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94185ab6b930'
down_revision: Union[str, None] = 'bd92dd5a3933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_state', sa.Column('paused_at', sa.Date(), nullable=True))
    op.add_column('pension_state', sa.Column('resume_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_state', 'resume_at')
    op.drop_column('pension_state', 'paused_at')
    # ### end Alembic commands ###
