"""add_value_to_statement_make_projections_nullable

Revision ID: 9ba22f8c3527
Revises: e998175a4989
Create Date: 2025-03-04 16:25:08.383601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba22f8c3527'
down_revision: Union[str, None] = 'e998175a4989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pension_company_retirement_projections', 'monthly_payout',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('pension_company_retirement_projections', 'total_capital',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('pension_company_statements', sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('pension_company_statements', sa.Column('note', sa.Text(), nullable=True))
    op.drop_column('pension_company_statements', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_company_statements', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pension_company_statements', 'note')
    op.drop_column('pension_company_statements', 'value')
    op.alter_column('pension_company_retirement_projections', 'total_capital',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('pension_company_retirement_projections', 'monthly_payout',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
