"""add_annual_salary_growth_rate_to_gap_config

Revision ID: 9e413bfe9e01
Revises: 4acc980b5028
Create Date: 2026-03-05 21:39:29.836923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e413bfe9e01'
down_revision: Union[str, None] = '4acc980b5028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_gap_config', sa.Column('annual_salary_growth_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='2.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retirement_gap_config', 'annual_salary_growth_rate')
    # ### end Alembic commands ###
