"""add_etf_update_tracking

Revision ID: a4f3babaddfb
Revises: ccb14d0eeb54
Create Date: 2025-02-22 20:28:26.334051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f3babaddfb'
down_revision: Union[str, None] = 'ccb14d0eeb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['etfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'error_type', 'date', name='uix_etf_error')
    )
    op.create_index('ix_etf_errors_resolved', 'etf_errors', ['resolved', 'resolved_at'], unique=False)
    op.create_table('etf_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.String(), nullable=False),
    sa.Column('update_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('missing_dates', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['etfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etf_updates_etf_id_date', 'etf_updates', ['etf_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_etf_updates_status_completed', 'etf_updates', ['status', 'completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_etf_updates_status_completed', table_name='etf_updates')
    op.drop_index('ix_etf_updates_etf_id_date', table_name='etf_updates')
    op.drop_table('etf_updates')
    op.drop_index('ix_etf_errors_resolved', table_name='etf_errors')
    op.drop_table('etf_errors')
    # ### end Alembic commands ###
