"""Modifying ETFPrices to save more data according to yfinance API

Revision ID: a625067e65c9
Revises: 4b10871053f4
Create Date: 2025-02-15 21:20:27.565910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a625067e65c9'
down_revision: Union[str, None] = '4b10871053f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etf_prices', sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('etf_prices', sa.Column('high', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('etf_prices', sa.Column('low', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('etf_prices', sa.Column('open', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('etf_prices', sa.Column('original_currency', sa.String(), nullable=True))
    op.create_unique_constraint('uix_etf_price_date', 'etf_prices', ['etf_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_etf_price_date', 'etf_prices', type_='unique')
    op.drop_column('etf_prices', 'original_currency')
    op.drop_column('etf_prices', 'open')
    op.drop_column('etf_prices', 'low')
    op.drop_column('etf_prices', 'high')
    op.drop_column('etf_prices', 'volume')
    # ### end Alembic commands ###
