"""Add Update Tracking v2

Revision ID: aa9697506e94
Revises: d012be10617a
Create Date: 2025-02-23 10:37:58.754842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9697506e94'
down_revision: Union[str, None] = 'd012be10617a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_update_tracking',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('attempted', sa.Boolean(), nullable=True),
    sa.Column('data_found', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'update_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_update_tracking')
    # ### end Alembic commands ###
