"""add_state_pension_tables

Revision ID: bde99be20c45
Revises: 1d43402c6c27
Create Date: 2025-03-17 20:37:48.643949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bde99be20c45'
down_revision: Union[str, None] = '1d43402c6c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', name='pensionstatus', create_type=False), nullable=False, server_default='ACTIVE'),
    sa.ForeignKeyConstraint(['member_id'], ['household_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_state_id'), 'pension_state', ['id'], unique=False)
    op.create_index(op.f('ix_pension_state_member_id'), 'pension_state', ['member_id'], unique=False)
    op.create_index('ix_pension_state_member_name', 'pension_state', ['member_id', 'name'], unique=True)
    op.create_table('pension_state_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('current_monthly_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('projected_monthly_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pension_id'], ['pension_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_state_statements_id'), 'pension_state_statements', ['id'], unique=False)
    op.create_index(op.f('ix_pension_state_statements_statement_date'), 'pension_state_statements', ['statement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pension_state_statements_statement_date'), table_name='pension_state_statements')
    op.drop_index(op.f('ix_pension_state_statements_id'), table_name='pension_state_statements')
    op.drop_table('pension_state_statements')
    op.drop_index('ix_pension_state_member_name', table_name='pension_state')
    op.drop_index(op.f('ix_pension_state_member_id'), table_name='pension_state')
    op.drop_index(op.f('ix_pension_state_id'), table_name='pension_state')
    op.drop_table('pension_state')
    # ### end Alembic commands ###
