"""add_exchange_rate_updates_table

Revision ID: ccb14d0eeb54
Revises: 2339bedbeb28
Create Date: 2025-02-22 15:13:19.403174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb14d0eeb54'
down_revision: Union[str, None] = '2339bedbeb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currencies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('missing_dates', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_rate_updates_status_completed', 'exchange_rate_updates', ['status', 'completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchange_rate_updates_status_completed', table_name='exchange_rate_updates')
    op.drop_table('exchange_rate_updates')
    # ### end Alembic commands ###
