"""update_company_pension_model

Revision ID: d723aa425c68
Revises: 37dc91afc559
Create Date: 2025-03-01 11:44:57.403246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd723aa425c68'
down_revision: Union[str, None] = '37dc91afc559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_company_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_company_id', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.Column('monthly_payout', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pension_company_id'], ['pension_company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_company_projections_id'), 'pension_company_projections', ['id'], unique=False)
    op.create_index('ix_pension_company_projections_pension_id', 'pension_company_projections', ['pension_company_id'], unique=False)
    op.add_column('pension_company', sa.Column('contribution_amount', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('pension_company', sa.Column('contribution_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY', 'ONE_TIME', name='contributionfrequency'), nullable=True))
    op.add_column('pension_company', sa.Column('latest_statement_date', sa.Date(), nullable=True))
    op.drop_column('pension_company', 'vesting_period')
    op.drop_column('pension_company', 'max_employer_contribution')
    op.drop_column('pension_company', 'matching_percentage')
    op.add_column('pension_company_contribution_history', sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False))
    op.drop_column('pension_company_contribution_history', 'employer_amount')
    op.drop_column('pension_company_contribution_history', 'employee_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_company_contribution_history', sa.Column('employee_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('pension_company_contribution_history', sa.Column('employer_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.drop_column('pension_company_contribution_history', 'amount')
    op.add_column('pension_company', sa.Column('matching_percentage', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('pension_company', sa.Column('max_employer_contribution', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.add_column('pension_company', sa.Column('vesting_period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pension_company', 'latest_statement_date')
    op.drop_column('pension_company', 'contribution_frequency')
    op.drop_column('pension_company', 'contribution_amount')
    op.drop_index('ix_pension_company_projections_pension_id', table_name='pension_company_projections')
    op.drop_index(op.f('ix_pension_company_projections_id'), table_name='pension_company_projections')
    op.drop_table('pension_company_projections')
    # ### end Alembic commands ###
