"""remove retirement_date from insurance pension

Revision ID: d741657e141a
Revises: 7a746d53ca0a
Create Date: 2025-03-06 13:28:54.429277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd741657e141a'
down_revision: Union[str, None] = '7a746d53ca0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pension_insurance', 'retirement_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_insurance', sa.Column('retirement_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
