"""Add scenario rates to Settings

Revision ID: d9fcb5ff43df
Revises: 783bca17d216
Create Date: 2025-02-25 20:22:48.656014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'd9fcb5ff43df'
down_revision: Union[str, None] = '783bca17d216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with server_default to handle existing rows
    op.add_column('settings', sa.Column('projection_pessimistic_rate', sa.Numeric(precision=10, scale=4), 
                                      nullable=False, server_default='4.0'))
    op.add_column('settings', sa.Column('projection_realistic_rate', sa.Numeric(precision=10, scale=4), 
                                      nullable=False, server_default='6.0'))
    op.add_column('settings', sa.Column('projection_optimistic_rate', sa.Numeric(precision=10, scale=4), 
                                      nullable=False, server_default='8.0'))

    # Remove server_default after columns are added
    op.alter_column('settings', 'projection_pessimistic_rate', 
                    server_default=None)
    op.alter_column('settings', 'projection_realistic_rate', 
                    server_default=None)
    op.alter_column('settings', 'projection_optimistic_rate', 
                    server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'projection_optimistic_rate')
    op.drop_column('settings', 'projection_realistic_rate')
    op.drop_column('settings', 'projection_pessimistic_rate')
    # ### end Alembic commands ###
