"""Adding more information to ETF History v2

Revision ID: e84ae794aeb6
Revises: 53ac1f6a6b42
Create Date: 2025-02-16 21:54:11.933507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84ae794aeb6'
down_revision: Union[str, None] = '53ac1f6a6b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etf_prices', sa.Column('dividends', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('etf_prices', sa.Column('stock_splits', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('etf_prices', sa.Column('capital_gains', sa.Numeric(precision=20, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etf_prices', 'capital_gains')
    op.drop_column('etf_prices', 'stock_splits')
    op.drop_column('etf_prices', 'dividends')
    # ### end Alembic commands ###
