"""Add pension company statements and retirement projections

Revision ID: e998175a4989
Revises: 196bff80076f
Create Date: 2025-03-01 21:43:21.403870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e998175a4989'
down_revision: Union[str, None] = '196bff80076f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_company_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pension_id'], ['pension_company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_company_statements_id'), 'pension_company_statements', ['id'], unique=False)
    op.create_table('pension_company_retirement_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.Column('monthly_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['pension_company_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_company_retirement_projections_id'), 'pension_company_retirement_projections', ['id'], unique=False)
    op.create_index('ix_pension_company_retirement_projections_statement_id', 'pension_company_retirement_projections', ['statement_id'], unique=False)
    op.drop_index('ix_pension_company_projections_id', table_name='pension_company_projections')
    op.drop_index('ix_pension_company_projections_pension_id', table_name='pension_company_projections')
    op.drop_table('pension_company_projections')
    op.drop_column('pension_company', 'latest_statement_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pension_company', sa.Column('latest_statement_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('pension_company_projections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pension_company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('retirement_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthly_payout', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_capital', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pension_company_id'], ['pension_company.id'], name='pension_company_projections_pension_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pension_company_projections_pkey')
    )
    op.create_index('ix_pension_company_projections_pension_id', 'pension_company_projections', ['pension_company_id'], unique=False)
    op.create_index('ix_pension_company_projections_id', 'pension_company_projections', ['id'], unique=False)
    op.drop_index('ix_pension_company_retirement_projections_statement_id', table_name='pension_company_retirement_projections')
    op.drop_index(op.f('ix_pension_company_retirement_projections_id'), table_name='pension_company_retirement_projections')
    op.drop_table('pension_company_retirement_projections')
    op.drop_index(op.f('ix_pension_company_statements_id'), table_name='pension_company_statements')
    op.drop_table('pension_company_statements')
    # ### end Alembic commands ###
