"""add pension savings contribution history

Revision ID: ee2c20c81e44
Revises: 7b8787db1216
Create Date: 2026-02-22 11:37:20.314842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2c20c81e44'
down_revision: Union[str, None] = '7b8787db1216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_savings_contribution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pension_savings_id', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pension_savings_id'], ['pension_savings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_savings_contribution_history_id'), 'pension_savings_contribution_history', ['id'], unique=False)
    op.create_index(op.f('ix_pension_savings_contribution_history_pension_savings_id'), 'pension_savings_contribution_history', ['pension_savings_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pension_savings_contribution_history_pension_savings_id'), table_name='pension_savings_contribution_history')
    op.drop_index(op.f('ix_pension_savings_contribution_history_id'), table_name='pension_savings_contribution_history')
    op.drop_table('pension_savings_contribution_history')
    # ### end Alembic commands ###
