"""add_pension_deduction_rate_to_gap_config

Revision ID: f331e8e8f325
Revises: 9e413bfe9e01
Create Date: 2026-03-05 21:51:03.276068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f331e8e8f325'
down_revision: Union[str, None] = '9e413bfe9e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_gap_config', sa.Column('pension_deduction_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retirement_gap_config', 'pension_deduction_rate')
    # ### end Alembic commands ###
